"""
04_artifact_annotation.py

STEP 4 — ARTIFACT CANDIDATE ANNOTATION AND VALIDATION
=====================================================

Purpose
-------
This stage converts the candidate events generated by
02_artifact_inspection.py into a human-validated artifact-event
dataset.

This script DOES NOT:

    - train an ML model
    - remove artifacts
    - classify fetal movement
    - modify raw signals
    - manufacture train/test splits

It provides the controlled bridge:

    candidate events
            ↓
    candidate inspection
            ↓
    human annotation
            ↓
    annotation quality control
            ↓
    validated artifact-event dataset

Allowed labels
--------------
    artifact
    likely_fetal
    uncertain

Blank / NaN
-----------
Means:

    not yet reviewed

Important
---------
For FOUR_IMU, the current dataset contains only ONE subject.

Therefore:

    subject-independent validation is NOT possible.

The script explicitly reports this.

A later record-independent exploratory experiment may use:

    record_id

as the grouping variable, but this must NOT be described
as subject-independent validation.
"""

from __future__ import annotations

import json
import math
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# ======================================================================
# PATHS
# ======================================================================

CURRENT_FILE = Path(__file__).resolve()

SRC_DIR = CURRENT_FILE.parent
PROJECT_ROOT = SRC_DIR.parent

DATA_ROOT = PROJECT_ROOT / "data"

INSPECTION_ROOT = (
    DATA_ROOT
    / "processed"
    / "artifact_inspection"
)

ANNOTATION_ROOT = (
    DATA_ROOT
    / "processed"
    / "artifact_annotation"
)

PLOTS_ROOT = (
    ANNOTATION_ROOT
    / "candidate_plots"
)

BATCH_ROOT = (
    ANNOTATION_ROOT
    / "batches"
)

REPORT_ROOT = (
    ANNOTATION_ROOT
    / "reports"
)

for directory in [
    ANNOTATION_ROOT,
    PLOTS_ROOT,
    BATCH_ROOT,
    REPORT_ROOT,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True,
    )


# ======================================================================
# CONFIGURATION
# ======================================================================

DATASET_NAME = "FOUR_IMU"

INPUT_FILE = (
    INSPECTION_ROOT
    / "four_imu_candidate_events.csv"
)

ANNOTATION_FILE = (
    ANNOTATION_ROOT
    / "four_imu_annotations.csv"
)

ML_READY_FILE = (
    ANNOTATION_ROOT
    / "four_imu_validated_events.csv"
)

GROUPING_REPORT_FILE = (
    REPORT_ROOT
    / "four_imu_grouping_report.json"
)

ANNOTATION_QC_FILE = (
    REPORT_ROOT
    / "four_imu_annotation_qc.csv"
)

BATCH_SIZE = 100

SAMPLING_RATE_HZ = 30.0

PLOT_WINDOW_PADDING_SECONDS = 2.0

MAX_PLOT_POINTS = 5000

VALID_LABELS = {
    "artifact",
    "likely_fetal",
    "uncertain",
}

VALID_CONFIDENCE = {
    "low",
    "medium",
    "high",
}


# ======================================================================
# DISPLAY
# ======================================================================

def print_header(title: str):

    print()
    print("=" * 80)
    print(title)
    print("=" * 80)


def print_section(title: str):

    print()
    print("-" * 80)
    print(title)
    print("-" * 80)


# ======================================================================
# INPUT VALIDATION
# ======================================================================

REQUIRED_COLUMNS = [
    "dataset",
    "record_identifier",
    "segment_id",
    "sample_count",
    "duration_seconds",
    "sampling_rate_hz",
    "candidate_artifact",
    "candidate_reason",
]


def validate_candidate_file(
    dataframe: pd.DataFrame,
):

    missing = [
        column
        for column in REQUIRED_COLUMNS
        if column not in dataframe.columns
    ]

    if missing:

        raise ValueError(
            "Candidate file is missing required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing
            )
        )


# ======================================================================
# CANDIDATE ID
# ======================================================================

def build_candidate_id(
    row: pd.Series,
    index: int,
) -> str:

    dataset = str(
        row.get(
            "dataset",
            DATASET_NAME,
        )
    )

    record = str(
        row.get(
            "record_identifier",
            "",
        )
    )

    segment = str(
        row.get(
            "segment_id",
            "",
        )
    )

    sensor = str(
        row.get(
            "sensor_id",
            "",
        )
    )

    return (
        f"{dataset}"
        f"__record_{record}"
        f"__segment_{segment}"
        f"__sensor_{sensor}"
        f"__candidate_{index + 1:05d}"
    )


# ======================================================================
# LOAD CANDIDATES
# ======================================================================

def load_candidates() -> pd.DataFrame:

    print(
        f"Input:\n{INPUT_FILE}"
    )

    if not INPUT_FILE.exists():

        raise FileNotFoundError(
            f"Candidate file not found:\n{INPUT_FILE}"
        )

    dataframe = pd.read_csv(
        INPUT_FILE
    )

    if dataframe.empty:

        raise ValueError(
            "Candidate file exists but contains zero rows."
        )

    validate_candidate_file(
        dataframe
    )

    dataframe = dataframe.copy()

    candidate_ids = []

    for index, row in dataframe.iterrows():

        candidate_ids.append(
            build_candidate_id(
                row,
                index,
            )
        )

    dataframe[
        "candidate_id"
    ] = candidate_ids

    return dataframe


# ======================================================================
# ANNOTATION SCHEMA
# ======================================================================

ANNOTATION_COLUMNS = [
    "candidate_id",
    "manual_label",
    "confidence",
    "artifact_type",
    "reviewer_notes",
    "reviewer",
    "annotation_timestamp_utc",
]


def create_annotation_columns(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:

    dataframe = dataframe.copy()

    for column in ANNOTATION_COLUMNS:

        if column not in dataframe.columns:

            dataframe[column] = ""

    return dataframe


# ======================================================================
# PRESERVE EXISTING ANNOTATIONS
# ======================================================================

def merge_previous_annotations(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:

    dataframe = create_annotation_columns(
        dataframe
    )

    if not ANNOTATION_FILE.exists():

        return dataframe

    previous = pd.read_csv(
        ANNOTATION_FILE
    )

    if (
        "candidate_id"
        not in previous.columns
    ):

        print(
            "WARNING: Existing annotation file "
            "has no candidate_id."
        )

        return dataframe

    previous = previous[
        [
            column
            for column in ANNOTATION_COLUMNS
            if column in previous.columns
        ]
    ].copy()

    merged = dataframe.drop(
        columns=[
            column
            for column in ANNOTATION_COLUMNS
            if column in dataframe.columns
        ],
        errors="ignore",
    ).merge(
        previous,
        on="candidate_id",
        how="left",
    )

    for column in ANNOTATION_COLUMNS:

        if column not in merged.columns:

            merged[column] = ""

    return merged


# ======================================================================
# SAVE ANNOTATIONS
# ======================================================================

def save_annotations(
    dataframe: pd.DataFrame,
):

    dataframe.to_csv(
        ANNOTATION_FILE,
        index=False,
    )

    print(
        f"Annotation registry saved:\n"
        f"{ANNOTATION_FILE}"
    )


# ======================================================================
# ANNOTATION STATUS
# ======================================================================

def normalize_label(
    value,
):

    if pd.isna(value):

        return None

    value = str(
        value
    ).strip().lower()

    if not value:

        return None

    aliases = {
        "artifact": "artifact",
        "likely_fetal": "likely_fetal",
        "likely fetal": "likely_fetal",
        "fetal": "likely_fetal",
        "uncertain": "uncertain",
        "unknown": "uncertain",
    }

    return aliases.get(
        value,
        None,
    )


def calculate_annotation_status(
    dataframe: pd.DataFrame,
):

    labels = dataframe[
        "manual_label"
    ].apply(
        normalize_label
    )

    total = len(
        dataframe
    )

    reviewed = int(
        labels.notna().sum()
    )

    artifact = int(
        (labels == "artifact").sum()
    )

    likely_fetal = int(
        (labels == "likely_fetal").sum()
    )

    uncertain = int(
        (labels == "uncertain").sum()
    )

    unlabeled = (
        total
        - reviewed
    )

    return {
        "total_candidates": total,
        "reviewed": reviewed,
        "unlabeled": unlabeled,
        "artifact": artifact,
        "likely_fetal": likely_fetal,
        "uncertain": uncertain,
        "completion_percent": (
            100.0 * reviewed / total
            if total
            else 0.0
        ),
    }


# ======================================================================
# GROUPING ANALYSIS
# ======================================================================

def determine_grouping_strategy(
    dataframe: pd.DataFrame,
):

    print_header(
        "FOUR_IMU INDEPENDENT GROUPING ANALYSIS"
    )

    report = {
        "dataset": DATASET_NAME,
        "dataset_name": "Fetal Movement Dataset Recorded Using Four IMUs",
        "subject_independent_validation_possible": False,
        "recommended_current_strategy": None,
        "warnings": [],
    }

    # --------------------------------------------------------------
    # SUBJECT
    # --------------------------------------------------------------

    if "subject_id" in dataframe.columns:

        subjects = (
            dataframe[
                "subject_id"
            ]
            .dropna()
            .astype(str)
            .unique()
            .tolist()
        )

    else:

        subjects = []

    report[
        "unique_subjects"
    ] = subjects

    report[
        "number_of_subjects"
    ] = len(subjects)

    print(
        f"Unique subjects represented in candidates: "
        f"{len(subjects)}"
    )

    if len(subjects) <= 1:

        print(
            "\n⚠ SUBJECT-INDEPENDENT VALIDATION IS NOT POSSIBLE."
        )

        report[
            "warnings"
        ].append(
            "Only one subject is available."
        )

        report[
            "recommended_current_strategy"
        ] = (
            "Do not report subject-independent ML validation. "
            "After annotation, use record-independent "
            "exploratory validation only if sufficient "
            "independent records exist."
        )

    else:

        report[
            "subject_independent_validation_possible"
        ] = True

        report[
            "recommended_current_strategy"
        ] = (
            "Group all folds by subject_id."
        )

    # --------------------------------------------------------------
    # RECORD
    # --------------------------------------------------------------

    record_column = None

    if "record_id" in dataframe.columns:

        record_column = "record_id"

    elif (
        "record_identifier"
        in dataframe.columns
    ):

        record_column = "record_identifier"

    report[
        "record_group_column"
    ] = record_column

    if record_column:

        records = (
            dataframe[
                record_column
            ]
            .dropna()
            .astype(str)
            .unique()
            .tolist()
        )

        report[
            "number_of_records"
        ] = len(records)

        report[
            "records"
        ] = records

        print(
            f"Unique records: {len(records)}"
        )

        if len(records) >= 2:

            print(
                "\n✓ Record-level grouping is available."
            )

            print(
                "  This can support RECORD-INDEPENDENT "
                "exploratory validation."
            )

            print(
                "  It must NOT be called subject-independent."
            )

            report[
                "record_independent_validation_possible"
            ] = True

        else:

            report[
                "record_independent_validation_possible"
            ] = False

            report[
                "warnings"
            ].append(
                "Fewer than two independent records available."
            )

    with open(
        GROUPING_REPORT_FILE,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            report,
            file,
            indent=4,
        )

    print(
        f"\nGrouping report saved:\n"
        f"{GROUPING_REPORT_FILE}"
    )

    return report


# ======================================================================
# CANDIDATE BATCHES
# ======================================================================

def create_annotation_batches(
    dataframe: pd.DataFrame,
):

    print_header(
        "CREATING ANNOTATION BATCHES"
    )

    dataframe = dataframe.copy()

    dataframe[
        "_annotation_index"
    ] = np.arange(
        len(dataframe)
    )

    number_of_batches = math.ceil(
        len(dataframe)
        /
        BATCH_SIZE
    )

    print(
        f"Candidates: {len(dataframe)}"
    )

    print(
        f"Batch size: {BATCH_SIZE}"
    )

    print(
        f"Batches: {number_of_batches}"
    )

    batch_paths = []

    for batch_number in range(
        number_of_batches
    ):

        start = (
            batch_number
            * BATCH_SIZE
        )

        end = min(
            start + BATCH_SIZE,
            len(dataframe),
        )

        batch = dataframe.iloc[
            start:end
        ].copy()

        batch_file = (
            BATCH_ROOT
            /
            f"four_imu_batch_"
            f"{batch_number + 1:03d}.csv"
        )

        batch.to_csv(
            batch_file,
            index=False,
        )

        batch_paths.append(
            batch_file
        )

    print(
        "\n✓ Annotation batches created."
    )

    return batch_paths


# ======================================================================
# SIGNAL LOADING
# ======================================================================

def load_four_imu_raw():

    """
    Import the existing production loader.

    This intentionally reuses the same loader used by
    loader_master_test.py and 02_artifact_inspection.py.
    """

    if str(SRC_DIR) not in sys.path:

        sys.path.insert(
            0,
            str(SRC_DIR),
        )

    from dataset import FourIMULoader

    class ConcreteFourIMULoader(
        FourIMULoader
    ):

        def standardize(
            self,
            data,
        ):

            return data

    raw_path = (
        DATA_ROOT
        / "raw"
        / "fetal"
        / "four_imu"
    )

    print(
        f"\nLoading FOUR_IMU raw dataset..."
    )

    loader = ConcreteFourIMULoader(
        raw_path
    )

    return loader.load()


# ======================================================================
# PLOT HELPERS
# ======================================================================

def downsample(
    x,
    y,
    maximum=MAX_PLOT_POINTS,
):

    x = np.asarray(
        x
    )

    y = np.asarray(
        y
    )

    if len(x) <= maximum:

        return x, y

    indices = np.linspace(
        0,
        len(x) - 1,
        maximum,
    ).astype(int)

    return (
        x[indices],
        y[indices],
    )


def numeric_array(
    series,
):

    return pd.to_numeric(
        series,
        errors="coerce",
    ).to_numpy(
        dtype=float
    )


def magnitude(
    dataframe,
    prefix,
):

    required = [
        f"{prefix}x",
        f"{prefix}y",
        f"{prefix}z",
    ]

    if not all(
        column in dataframe.columns
        for column in required
    ):

        return None

    x = numeric_array(
        dataframe[
            required[0]
        ]
    )

    y = numeric_array(
        dataframe[
            required[1]
        ]
    )

    z = numeric_array(
        dataframe[
            required[2]
        ]
    )

    return np.sqrt(
        x ** 2
        + y ** 2
        + z ** 2
    )


# ======================================================================
# CANDIDATE SIGNAL EXTRACTION
# ======================================================================

def extract_candidate_signal(
    raw_data: pd.DataFrame,
    candidate: pd.Series,
):

    record_id = str(
        candidate[
            "record_identifier"
        ]
    )

    sensor_id = str(
        candidate.get(
            "sensor_id",
            "",
        )
    )

    segment_id = candidate[
        "segment_id"
    ]

    subset = raw_data.copy()

    # --------------------------------------------------------------
    # Match record
    # --------------------------------------------------------------

    if "record_id" in subset.columns:

        subset = subset[
            subset[
                "record_id"
            ].astype(str)
            == record_id
        ]

    else:

        subset = subset[
            subset[
                "record_identifier"
            ].astype(str)
            == record_id
        ]

    # --------------------------------------------------------------
    # Match sensor
    # --------------------------------------------------------------

    if (
        sensor_id
        and
        "sensor_id"
        in subset.columns
    ):

        subset = subset[
            subset[
                "sensor_id"
            ].astype(str)
            == sensor_id
        ]

    # --------------------------------------------------------------
    # Segment identification
    #
    # The current candidate file does not explicitly
    # save segment start/end timestamps.
    #
    # Therefore we reconstruct the segment context
    # from the record stream.
    # --------------------------------------------------------------

    if subset.empty:

        return subset

    subset = subset.sort_values(
        "timestamp"
    )

    return subset


# ======================================================================
# PLOT ONE CANDIDATE
# ======================================================================

def plot_candidate(
    raw_data: pd.DataFrame,
    candidate: pd.Series,
    output_path: Path,
):

    signal = extract_candidate_signal(
        raw_data,
        candidate,
    )

    if signal.empty:

        return False

    timestamps = pd.to_numeric(
        signal["timestamp"],
        errors="coerce",
    ).to_numpy(
        dtype=float
    )

    valid = np.isfinite(
        timestamps
    )

    signal = signal.loc[
        valid
    ].copy()

    timestamps = timestamps[
        valid
    ]

    if len(signal) < 2:

        return False

    relative_time = (
        timestamps
        - timestamps[0]
    )

    fig, axes = plt.subplots(
        2,
        1,
        figsize=(14, 8),
        sharex=True,
    )

    # --------------------------------------------------------------
    # ACCELERATION
    # --------------------------------------------------------------

    for column in [
        "ax",
        "ay",
        "az",
    ]:

        if column not in signal.columns:

            continue

        values = numeric_array(
            signal[column]
        )

        x, y = downsample(
            relative_time,
            values,
        )

        axes[0].plot(
            x,
            y,
            label=column,
            linewidth=0.8,
        )

    acc_mag = magnitude(
        signal,
        "a",
    )

    if acc_mag is not None:

        x, y = downsample(
            relative_time,
            acc_mag,
        )

        axes[0].plot(
            x,
            y,
            label="acc_magnitude",
            linewidth=1.5,
        )

    axes[0].set_ylabel(
        "Acceleration"
    )

    axes[0].set_title(
        "Accelerometer"
    )

    axes[0].legend()

    axes[0].grid(
        alpha=0.25
    )

    # --------------------------------------------------------------
    # GYROSCOPE
    # --------------------------------------------------------------

    for column in [
        "gx",
        "gy",
        "gz",
    ]:

        if column not in signal.columns:

            continue

        values = numeric_array(
            signal[column]
        )

        x, y = downsample(
            relative_time,
            values,
        )

        axes[1].plot(
            x,
            y,
            label=column,
            linewidth=0.8,
        )

    gyro_mag = magnitude(
        signal,
        "g",
    )

    if gyro_mag is not None:

        x, y = downsample(
            relative_time,
            gyro_mag,
        )

        axes[1].plot(
            x,
            y,
            label="gyro_magnitude",
            linewidth=1.5,
        )

    axes[1].set_ylabel(
        "Gyroscope"
    )

    axes[1].set_xlabel(
        "Time within record (s)"
    )

    axes[1].set_title(
        "Gyroscope"
    )

    axes[1].legend()

    axes[1].grid(
        alpha=0.25
    )

    candidate_id = candidate[
        "candidate_id"
    ]

    reason = candidate.get(
        "candidate_reason",
        "",
    )

    fig.suptitle(
        (
            f"FOUR_IMU Candidate\n"
            f"{candidate_id}\n"
            f"Reason: {reason}"
        ),
        fontsize=12,
    )

    fig.tight_layout()

    fig.savefig(
        output_path,
        dpi=140,
        bbox_inches="tight",
    )

    plt.close(
        fig
    )

    return True


# ======================================================================
# PLOT GENERATION
# ======================================================================

def generate_candidate_plots(
    dataframe: pd.DataFrame,
):

    print_header(
        "GENERATING FOUR_IMU CANDIDATE INSPECTION PLOTS"
    )

    raw_data = load_four_imu_raw()

    print(
        f"Raw shape: {raw_data.shape}"
    )

    generated = 0

    failed = 0

    for index, candidate in dataframe.iterrows():

        candidate_id = candidate[
            "candidate_id"
        ]

        filename = (
            f"{index + 1:05d}_"
            f"{candidate_id.replace('/', '_')}.png"
        )

        output_path = (
            PLOTS_ROOT
            / filename
        )

        if output_path.exists():

            generated += 1
            continue

        try:

            success = plot_candidate(
                raw_data,
                candidate,
                output_path,
            )

            if success:

                generated += 1

            else:

                failed += 1

        except Exception as exc:

            failed += 1

            print(
                f"Failed candidate "
                f"{candidate_id}: "
                f"{repr(exc)}"
            )

        if (
            (index + 1) % 100
            == 0
        ):

            print(
                f"  Processed "
                f"{index + 1}/{len(dataframe)}"
            )

    print()
    print(
        f"Plots available: {generated}"
    )

    print(
        f"Plot failures: {failed}"
    )


# ======================================================================
# QUALITY CONTROL
# ======================================================================

def generate_qc_report(
    dataframe: pd.DataFrame,
):

    status = calculate_annotation_status(
        dataframe
    )

    rows = []

    labels = dataframe[
        "manual_label"
    ].apply(
        normalize_label
    )

    rows.append(
        {
            "dataset": DATASET_NAME,
            "metric": "total_candidates",
            "value": status[
                "total_candidates"
            ],
        }
    )

    rows.append(
        {
            "dataset": DATASET_NAME,
            "metric": "reviewed",
            "value": status[
                "reviewed"
            ],
        }
    )

    rows.append(
        {
            "dataset": DATASET_NAME,
            "metric": "unlabeled",
            "value": status[
                "unlabeled"
            ],
        }
    )

    rows.append(
        {
            "dataset": DATASET_NAME,
            "metric": "artifact",
            "value": status[
                "artifact"
            ],
        }
    )

    rows.append(
        {
            "dataset": DATASET_NAME,
            "metric": "likely_fetal",
            "value": status[
                "likely_fetal"
            ],
        }
    )

    rows.append(
        {
            "dataset": DATASET_NAME,
            "metric": "uncertain",
            "value": status[
                "uncertain"
            ],
        }
    )

    rows.append(
        {
            "dataset": DATASET_NAME,
            "metric": "completion_percent",
            "value": status[
                "completion_percent"
            ],
        }
    )

    qc = pd.DataFrame(
        rows
    )

    qc.to_csv(
        ANNOTATION_QC_FILE,
        index=False,
    )

    return status


# ======================================================================
# VALIDATED ML DATASET
# ======================================================================

def create_validated_ml_dataset(
    dataframe: pd.DataFrame,
):

    labels = dataframe[
        "manual_label"
    ].apply(
        normalize_label
    )

    validated = dataframe.copy()

    validated[
        "normalized_label"
    ] = labels

    # --------------------------------------------------------------
    # Do NOT include uncertain events as supervised examples.
    # --------------------------------------------------------------

    validated = validated[
        labels.isin(
            {
                "artifact",
                "likely_fetal",
            }
        )
    ].copy()

    if validated.empty:

        print(
            "\nNo supervised events available yet."
        )

        return validated

    validated[
        "artifact_target"
    ] = (
        validated[
            "normalized_label"
        ]
        == "artifact"
    ).astype(int)

    validated.to_csv(
        ML_READY_FILE,
        index=False,
    )

    print(
        f"\nValidated ML dataset saved:\n"
        f"{ML_READY_FILE}"
    )

    print(
        "\nValidated label distribution:"
    )

    print(
        validated[
            "normalized_label"
        ].value_counts()
    )

    return validated


# ======================================================================
# MAIN
# ======================================================================

def main():

    print_header(
        "STEP 4 — ARTIFACT CANDIDATE ANNOTATION PIPELINE"
    )

    print(
        """
This stage validates candidate artifact events before ML.

No artifact removal is performed.
No ML model is trained.
No train/test split is manufactured.
No subject-independent claim is made for a single-subject dataset.
"""
    )

    # --------------------------------------------------------------
    # LOAD
    # --------------------------------------------------------------

    candidates = load_candidates()

    print(
        f"\nCandidates loaded: "
        f"{len(candidates)}"
    )

    # --------------------------------------------------------------
    # ANNOTATION REGISTRY
    # --------------------------------------------------------------

    candidates = merge_previous_annotations(
        candidates
    )

    save_annotations(
        candidates
    )

    # --------------------------------------------------------------
    # GROUPING ANALYSIS
    # --------------------------------------------------------------

    determine_grouping_strategy(
        candidates
    )

    # --------------------------------------------------------------
    # CREATE BATCHES
    # --------------------------------------------------------------

    create_annotation_batches(
        candidates
    )

    # --------------------------------------------------------------
    # PLOTS
    # --------------------------------------------------------------

    generate_candidate_plots(
        candidates
    )

    # --------------------------------------------------------------
    # QC
    # --------------------------------------------------------------

    status = generate_qc_report(
        candidates
    )

    print_header(
        "ANNOTATION STATUS"
    )

    print(
        f"Total candidates : "
        f"{status['total_candidates']}"
    )

    print(
        f"Reviewed         : "
        f"{status['reviewed']}"
    )

    print(
        f"Unlabeled        : "
        f"{status['unlabeled']}"
    )

    print(
        f"Artifact         : "
        f"{status['artifact']}"
    )

    print(
        f"Likely fetal     : "
        f"{status['likely_fetal']}"
    )

    print(
        f"Uncertain        : "
        f"{status['uncertain']}"
    )

    print(
        f"Completion       : "
        f"{status['completion_percent']:.2f}%"
    )

    # --------------------------------------------------------------
    # VALIDATED DATASET
    # --------------------------------------------------------------

    validated = create_validated_ml_dataset(
        candidates
    )

    # --------------------------------------------------------------
    # FINAL
    # --------------------------------------------------------------

    print_header(
        "STEP 4 PIPELINE READY"
    )

    print(
        f"""
Annotation registry:
    {ANNOTATION_FILE}

Candidate plots:
    {PLOTS_ROOT}

Annotation batches:
    {BATCH_ROOT}

QC report:
    {ANNOTATION_QC_FILE}

Grouping report:
    {GROUPING_REPORT_FILE}

Validated ML dataset:
    {ML_READY_FILE}
"""
    )

    if validated.empty:

        print(
            """
NEXT ACTION:

Manually annotate the FOUR_IMU candidates.

Do NOT run artifact ML yet.

Once sufficient candidates have been labeled,
rerun this script and inspect the annotation QC.
"""
        )

    else:

        print(
            """
Supervised events now exist.

Before ML:

1. Inspect label balance.
2. Inspect labels by record_id.
3. Check for records containing only one class.
4. Confirm that labels represent genuinely independent
   artifact/fetal decisions.
5. Then configure record-independent exploratory validation.
"""
        )


# ======================================================================
# ENTRY POINT
# ======================================================================

if __name__ == "__main__":

    main()