"""
Artifact ML Baseline + Subject-Independent Validation
======================================================

Purpose
-------
Train baseline machine-learning models for artifact-event
classification using the manually validated candidate events
generated by the artifact inspection layer.

This module implements:

    Step 5
    -------
    Baseline artifact models:
        - Logistic Regression
        - Random Forest
        - SVM
        - XGBoost

    Step 6
    -------
    Subject-independent validation.

Scientific principle
--------------------
The artifact detector must learn from event-level features rather
than raw signal samples.

Events belonging to the same subject must never be split between
training and testing folds.

Current dataset constraints
---------------------------
COUGH
    13 subjects
    Subject-independent validation is possible.

FOUR_IMU
    1 subject
    Subject-independent validation is NOT possible.

OXFORD
    1 subject
    Currently no candidate events were generated.

Therefore:
    COUGH -> supervised subject-independent ML experiment
    FOUR_IMU -> reported as insufficient for subject-independent ML
    OXFORD -> reported as no candidate events / insufficient data

Label policy
------------
The manual annotation taxonomy is expected to contain:

    artifact
    likely_fetal
    uncertain

For the first supervised binary baseline:

    artifact       -> 1
    likely_fetal   -> 0
    uncertain      -> excluded

Unlabeled events are also excluded.

Important
---------
This script does NOT perform artifact removal.

It only learns an artifact-event classifier.

Output
------
data/processed/artifact_ml/

    dataset_validation.csv
    model_comparison.csv
    fold_results.csv
    predictions.csv
    feature_importance.csv
    experiment_summary.txt
    models/
        <dataset>_<model>.joblib

Author
------
Fetal Movement Assessment Project
"""


from __future__ import annotations

import json
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC


# ============================================================
# OPTIONAL XGBOOST
# ============================================================

try:
    from xgboost import XGBClassifier

    XGBOOST_AVAILABLE = True

except ImportError:
    XGBOOST_AVAILABLE = False


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(
    r"C:\Users\Asus\OneDrive\Desktop\fetal_assesment_project"
)

INPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "artifact_inspection"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "artifact_ml"
)

MODEL_DIR = OUTPUT_DIR / "models"


# ============================================================
# INPUT DATASETS
# ============================================================

DATASET_FILES = {
    "COUGH": (
        INPUT_DIR
        / "cough_candidate_events.csv"
    ),

    "FOUR_IMU": (
        INPUT_DIR
        / "four_imu_candidate_events.csv"
    ),

    "OXFORD": (
        INPUT_DIR
        / "oxford_candidate_events.csv"
    ),
}


# ============================================================
# LABEL CONFIGURATION
# ============================================================

ARTIFACT_LABEL = "artifact"

FETAL_LABEL = "likely_fetal"

UNCERTAIN_LABEL = "uncertain"


# ============================================================
# POSSIBLE LABEL COLUMN NAMES
# ============================================================

LABEL_COLUMN_CANDIDATES = [
    "candidate_label",
    "manual_label",
    "artifact_label",
    "annotation",
    "label",
    "class",
    "target",
]


# ============================================================
# POSSIBLE SUBJECT COLUMN NAMES
# ============================================================

SUBJECT_COLUMN_CANDIDATES = [
    "subject_id",
    "subject",
    "participant_id",
    "participant",
    "user_id",
    "user",
]


# ============================================================
# METADATA / NON-FEATURE COLUMNS
# ============================================================

NON_FEATURE_COLUMNS = {
    # identifiers
    "subject_id",
    "subject",
    "participant_id",
    "participant",
    "user_id",
    "user",

    "record_id",
    "record",
    "recording_id",

    "sensor_id",
    "sensor",

    "dataset_source",
    "dataset",
    "source",

    "sub_dataset",

    "event_id",
    "candidate_id",
    "segment_id",

    # temporal identifiers
    "start",
    "end",
    "start_time",
    "end_time",
    "timestamp",
    "time",

    # target
    "candidate_label",
    "manual_label",
    "artifact_label",
    "annotation",
    "label",
    "class",
    "target",

    # paths / plotting metadata
    "plot_path",
    "figure_path",
    "file_path",
    "path",

    # free text
    "notes",
    "comment",
    "comments",
}


# ============================================================
# REPRODUCIBILITY
# ============================================================

RANDOM_STATE = 42


# ============================================================
# VALIDATION CONFIGURATION
# ============================================================

MIN_SUBJECTS_FOR_GROUP_CV = 3

MAX_FOLDS = 5


# ============================================================
# DISPLAY HELPERS
# ============================================================

def print_header(title: str) -> None:
    """Print a consistent section header."""

    print("\n")
    print("=" * 80)
    print(title)
    print("=" * 80)


def print_subheader(title: str) -> None:
    """Print a smaller section header."""

    print("\n" + "-" * 80)
    print(title)
    print("-" * 80)


# ============================================================
# DIRECTORY SETUP
# ============================================================

def create_output_directories() -> None:
    """Create all required output directories."""

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    MODEL_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


# ============================================================
# COLUMN DETECTION
# ============================================================

def find_existing_column(
    columns,
    candidates: List[str],
) -> Optional[str]:
    """
    Find the first matching column using case-insensitive
    exact matching followed by normalized matching.
    """

    normalized = {
        str(column).strip().lower(): column
        for column in columns
    }

    # Exact matching
    for candidate in candidates:

        key = candidate.strip().lower()

        if key in normalized:
            return normalized[key]

    # Normalized matching
    for column in columns:

        column_normalized = (
            str(column)
            .strip()
            .lower()
            .replace(" ", "_")
            .replace("-", "_")
        )

        for candidate in candidates:

            candidate_normalized = (
                candidate
                .strip()
                .lower()
                .replace(" ", "_")
                .replace("-", "_")
            )

            if column_normalized == candidate_normalized:
                return column

    return None


def detect_label_column(
    df: pd.DataFrame,
) -> Optional[str]:
    """Detect the supervised annotation column."""

    return find_existing_column(
        df.columns,
        LABEL_COLUMN_CANDIDATES,
    )


def detect_subject_column(
    df: pd.DataFrame,
) -> Optional[str]:
    """Detect the subject identifier column."""

    return find_existing_column(
        df.columns,
        SUBJECT_COLUMN_CANDIDATES,
    )


# ============================================================
# LABEL NORMALIZATION
# ============================================================

def normalize_label(value) -> Optional[str]:
    """
    Normalize manual annotation labels.

    Returns
    -------
    artifact
    likely_fetal
    uncertain
    None
    """

    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    if not value:
        return None

    value = value.replace("-", "_")
    value = value.replace(" ", "_")

    if value in {
        "artifact",
        "artefact",
        "artifactual",
        "1",
    }:
        return ARTIFACT_LABEL

    if value in {
        "likely_fetal",
        "fetal",
        "likely_fetal_movement",
        "movement",
        "non_artifact",
        "nonartifact",
        "0",
    }:
        return FETAL_LABEL

    if value in {
        "uncertain",
        "unknown",
        "unsure",
        "?",
    }:
        return UNCERTAIN_LABEL

    return value


# ============================================================
# LOAD CANDIDATE EVENTS
# ============================================================

def load_candidate_events(
    dataset_name: str,
    path: Path,
) -> pd.DataFrame:
    """
    Load a candidate-event CSV.
    """

    if not path.exists():

        raise FileNotFoundError(
            f"{dataset_name} candidate-event file does not exist:\n"
            f"{path}"
        )

    df = pd.read_csv(path)

    if df.empty:

        print(
            f"{dataset_name}: candidate-event file is empty."
        )

    return df


# ============================================================
# DATASET PREPARATION
# ============================================================

def prepare_dataset(
    dataset_name: str,
    raw_df: pd.DataFrame,
) -> Dict:
    """
    Prepare one dataset for supervised artifact classification.

    Returns a dictionary containing:

        full dataframe
        labeled dataframe
        feature dataframe
        target
        groups
        metadata
    """

    print_subheader(
        f"{dataset_name} DATASET PREPARATION"
    )

    df = raw_df.copy()

    print(
        f"Raw candidate events: {len(df):,}"
    )

    # --------------------------------------------------------
    # Label column
    # --------------------------------------------------------

    label_column = detect_label_column(df)

    if label_column is None:

        print(
            "❌ No manual label column detected."
        )

        return {
            "status": "NO_LABEL_COLUMN",
            "dataset": dataset_name,
            "raw": df,
        }

    print(
        f"Label column: {label_column}"
    )

    # --------------------------------------------------------
    # Normalize labels
    # --------------------------------------------------------

    df["_normalized_label"] = (
        df[label_column]
        .apply(normalize_label)
    )

    print("\nRaw label distribution:")

    print(
        df[label_column]
        .value_counts(dropna=False)
    )

    print("\nNormalized label distribution:")

    print(
        df["_normalized_label"]
        .value_counts(dropna=False)
    )

    # --------------------------------------------------------
    # Subject
    # --------------------------------------------------------

    subject_column = detect_subject_column(df)

    if subject_column is None:

        print(
            "❌ Subject identifier column not found."
        )

        return {
            "status": "NO_SUBJECT_COLUMN",
            "dataset": dataset_name,
            "raw": df,
        }

    print(
        f"Subject column: {subject_column}"
    )

    # --------------------------------------------------------
    # Keep only supervised labels
    # --------------------------------------------------------

    usable_mask = df["_normalized_label"].isin(
        [
            ARTIFACT_LABEL,
            FETAL_LABEL,
        ]
    )

    supervised = (
        df.loc[usable_mask]
        .copy()
        .reset_index(drop=True)
    )

    uncertain_count = (
        df["_normalized_label"]
        .eq(UNCERTAIN_LABEL)
        .sum()
    )

    unlabeled_count = (
        df["_normalized_label"]
        .isna()
        .sum()
    )

    print(
        f"\nUncertain events excluded: "
        f"{uncertain_count:,}"
    )

    print(
        f"Unlabeled/unknown events excluded: "
        f"{unlabeled_count:,}"
    )

    print(
        f"Supervised events: "
        f"{len(supervised):,}"
    )

    if supervised.empty:

        return {
            "status": "NO_SUPERVISED_EVENTS",
            "dataset": dataset_name,
            "raw": df,
            "supervised": supervised,
        }

    # --------------------------------------------------------
    # Target
    # --------------------------------------------------------

    y = (
        supervised["_normalized_label"]
        .map({
            ARTIFACT_LABEL: 1,
            FETAL_LABEL: 0,
        })
        .astype(int)
    )

    # --------------------------------------------------------
    # Subject groups
    # --------------------------------------------------------

    groups = (
        supervised[subject_column]
        .astype(str)
    )

    # --------------------------------------------------------
    # Feature candidates
    # --------------------------------------------------------

    excluded_columns = set(
        NON_FEATURE_COLUMNS
    )

    excluded_columns.update(
        {
            label_column,
            "_normalized_label",
            subject_column,
        }
    )

    numeric_columns = (
        supervised
        .select_dtypes(
            include=[np.number]
        )
        .columns
        .tolist()
    )

    feature_columns = [
        column
        for column in numeric_columns
        if column not in excluded_columns
    ]

    # Remove columns with no variability
    valid_feature_columns = []

    for column in feature_columns:

        unique_count = (
            supervised[column]
            .nunique(dropna=True)
        )

        if unique_count <= 1:
            continue

        valid_feature_columns.append(column)

    feature_columns = valid_feature_columns

    print(
        f"\nNumeric feature candidates: "
        f"{len(numeric_columns)}"
    )

    print(
        f"Usable feature columns: "
        f"{len(feature_columns)}"
    )

    if feature_columns:

        print("\nFeatures:")

        for column in feature_columns:

            print(
                f"  - {column}"
            )

    if not feature_columns:

        print(
            "\n❌ No usable numeric features found."
        )

        return {
            "status": "NO_FEATURES",
            "dataset": dataset_name,
            "raw": df,
            "supervised": supervised,
        }

    X = (
        supervised[feature_columns]
        .replace(
            [np.inf, -np.inf],
            np.nan,
        )
        .copy()
    )

    # --------------------------------------------------------
    # Feature completeness
    # --------------------------------------------------------

    missing_percent = (
        X.isna()
        .mean()
        .mul(100)
        .sort_values(
            ascending=False
        )
    )

    print("\nFeature missingness:")

    print(
        missing_percent
        .to_string()
    )

    # --------------------------------------------------------
    # Class distribution
    # --------------------------------------------------------

    print("\nClass distribution:")

    class_counts = (
        y.value_counts()
        .sort_index()
    )

    print(
        f"Fetal/non-artifact (0): "
        f"{class_counts.get(0, 0):,}"
    )

    print(
        f"Artifact (1): "
        f"{class_counts.get(1, 0):,}"
    )

    # --------------------------------------------------------
    # Subject distribution
    # --------------------------------------------------------

    subject_counts = (
        groups
        .value_counts()
        .sort_index()
    )

    print(
        f"\nUnique subjects: "
        f"{groups.nunique()}"
    )

    print(
        "\nEvents per subject:"
    )

    print(
        subject_counts
        .to_string()
    )

    return {
        "status": "READY",
        "dataset": dataset_name,
        "raw": df,
        "supervised": supervised,
        "X": X,
        "y": y,
        "groups": groups,
        "feature_columns": feature_columns,
        "label_column": label_column,
        "subject_column": subject_column,
        "uncertain_count": uncertain_count,
        "unlabeled_count": unlabeled_count,
        "class_counts": class_counts.to_dict(),
        "subject_count": groups.nunique(),
    }


# ============================================================
# MODEL BUILDERS
# ============================================================

def build_models(
    n_positive: int,
) -> Dict[str, object]:
    """
    Construct baseline classifiers.

    Models:
        Logistic Regression
        Random Forest
        SVM
        XGBoost
    """

    models = {}

    # --------------------------------------------------------
    # Logistic Regression
    # --------------------------------------------------------

    models["LogisticRegression"] = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(
                    strategy="median"
                ),
            ),

            (
                "scaler",
                StandardScaler(),
            ),

            (
                "classifier",
                LogisticRegression(
                    max_iter=2000,
                    class_weight="balanced",
                    random_state=RANDOM_STATE,
                ),
            ),
        ]
    )

    # --------------------------------------------------------
    # Random Forest
    # --------------------------------------------------------

    models["RandomForest"] = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(
                    strategy="median"
                ),
            ),

            (
                "classifier",
                RandomForestClassifier(
                    n_estimators=300,
                    max_depth=None,
                    min_samples_leaf=2,
                    class_weight="balanced",
                    random_state=RANDOM_STATE,
                    n_jobs=-1,
                ),
            ),
        ]
    )

    # --------------------------------------------------------
    # SVM
    # --------------------------------------------------------

    models["SVM"] = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(
                    strategy="median"
                ),
            ),

            (
                "scaler",
                StandardScaler(),
            ),

            (
                "classifier",
                SVC(
                    probability=True,
                    class_weight="balanced",
                    random_state=RANDOM_STATE,
                ),
            ),
        ]
    )

    # --------------------------------------------------------
    # XGBoost
    # --------------------------------------------------------

    if XGBOOST_AVAILABLE:

        models["XGBoost"] = Pipeline(
            steps=[
                (
                    "imputer",
                    SimpleImputer(
                        strategy="median"
                    ),
                ),

                (
                    "classifier",
                    XGBClassifier(
                        n_estimators=300,
                        max_depth=5,
                        learning_rate=0.05,
                        subsample=0.8,
                        colsample_bytree=0.8,
                        objective="binary:logistic",
                        eval_metric="logloss",
                        random_state=RANDOM_STATE,
                        n_jobs=-1,
                    ),
                ),
            ]
        )

    else:

        print(
            "\n⚠ XGBoost is not installed."
        )

        print(
            "Install it with:"
        )

        print(
            "pip install xgboost"
        )

    return models


# ============================================================
# PROBABILITY EXTRACTION
# ============================================================

def get_prediction_scores(
    model,
    X,
) -> np.ndarray:
    """
    Obtain continuous scores for ROC-AUC / PR-AUC.
    """

    if hasattr(
        model,
        "predict_proba",
    ):

        probabilities = (
            model.predict_proba(X)
        )

        return probabilities[:, 1]

    if hasattr(
        model,
        "decision_function",
    ):

        return (
            model
            .decision_function(X)
        )

    return (
        model
        .predict(X)
        .astype(float)
    )


# ============================================================
# METRICS
# ============================================================

def calculate_metrics(
    y_true,
    y_pred,
    y_score,
) -> Dict[str, float]:
    """
    Calculate binary classification metrics.
    """

    metrics = {
        "accuracy": accuracy_score(
            y_true,
            y_pred,
        ),

        "precision": precision_score(
            y_true,
            y_pred,
            zero_division=0,
        ),

        "recall": recall_score(
            y_true,
            y_pred,
            zero_division=0,
        ),

        "f1": f1_score(
            y_true,
            y_pred,
            zero_division=0,
        ),
    }

    # --------------------------------------------------------
    # ROC-AUC
    # --------------------------------------------------------

    if len(np.unique(y_true)) == 2:

        try:

            metrics["roc_auc"] = (
                roc_auc_score(
                    y_true,
                    y_score,
                )
            )

        except Exception:

            metrics["roc_auc"] = np.nan

        try:

            metrics["pr_auc"] = (
                average_precision_score(
                    y_true,
                    y_score,
                )
            )

        except Exception:

            metrics["pr_auc"] = np.nan

    else:

        metrics["roc_auc"] = np.nan
        metrics["pr_auc"] = np.nan

    return metrics


# ============================================================
# SUBJECT-INDEPENDENT CV
# ============================================================

def run_subject_independent_cv(
    dataset_name: str,
    X: pd.DataFrame,
    y: pd.Series,
    groups: pd.Series,
    feature_columns: List[str],
) -> Tuple[
    pd.DataFrame,
    pd.DataFrame,
    Dict[str, object],
]:
    """
    Run subject-independent GroupKFold validation.

    Returns
    -------
    fold_results
    predictions
    fitted_models
    """

    print_header(
        f"{dataset_name} — SUBJECT-INDEPENDENT VALIDATION"
    )

    n_subjects = groups.nunique()

    print(
        f"Unique subjects: {n_subjects}"
    )

    # --------------------------------------------------------
    # Scientific validity check
    # --------------------------------------------------------

    if n_subjects < MIN_SUBJECTS_FOR_GROUP_CV:

        print(
            "\n⚠ Subject-independent validation "
            "cannot be performed."
        )

        print(
            f"Required subjects: "
            f">= {MIN_SUBJECTS_FOR_GROUP_CV}"
        )

        print(
            f"Available subjects: "
            f"{n_subjects}"
        )

        return (
            pd.DataFrame(),
            pd.DataFrame(),
            {},
        )

    n_splits = min(
        MAX_FOLDS,
        n_subjects,
    )

    cv = GroupKFold(
        n_splits=n_splits
    )

    models = build_models(
        int(y.sum())
    )

    fold_results = []
    prediction_records = []
    fitted_models = {}

    # --------------------------------------------------------
    # Model loop
    # --------------------------------------------------------

    for model_name, model in models.items():

        print_subheader(
            f"{dataset_name} — {model_name}"
        )

        model_fold_results = []

        for fold, (
            train_idx,
            test_idx,
        ) in enumerate(
            cv.split(
                X,
                y,
                groups,
            ),
            start=1,
        ):

            X_train = X.iloc[train_idx]
            X_test = X.iloc[test_idx]

            y_train = y.iloc[train_idx]
            y_test = y.iloc[test_idx]

            train_groups = (
                groups.iloc[train_idx]
            )

            test_groups = (
                groups.iloc[test_idx]
            )

            # ------------------------------------------------
            # Explicit leakage check
            # ------------------------------------------------

            overlap = (
                set(train_groups)
                &
                set(test_groups)
            )

            if overlap:

                raise RuntimeError(
                    "Subject leakage detected! "
                    f"Overlapping subjects: {overlap}"
                )

            # ------------------------------------------------
            # Check both classes in training
            # ------------------------------------------------

            if y_train.nunique() < 2:

                print(
                    f"Fold {fold}: skipped because "
                    f"training data contains only one class."
                )

                continue

            # ------------------------------------------------
            # Clone model
            # ------------------------------------------------

            fold_model = clone(model)

            # ------------------------------------------------
            # Train
            # ------------------------------------------------

            fold_model.fit(
                X_train,
                y_train,
            )

            # ------------------------------------------------
            # Predict
            # ------------------------------------------------

            y_pred = (
                fold_model
                .predict(X_test)
            )

            y_score = (
                get_prediction_scores(
                    fold_model,
                    X_test,
                )
            )

            # ------------------------------------------------
            # Metrics
            # ------------------------------------------------

            metrics = calculate_metrics(
                y_test,
                y_pred,
                y_score,
            )

            metrics.update(
                {
                    "dataset": dataset_name,
                    "model": model_name,
                    "fold": fold,
                    "train_events": len(train_idx),
                    "test_events": len(test_idx),
                    "train_subjects": len(
                        set(train_groups)
                    ),
                    "test_subjects": len(
                        set(test_groups)
                    ),
                    "test_subject_ids": ",".join(
                        sorted(
                            set(
                                test_groups.astype(str)
                            )
                        )
                    ),
                }
            )

            fold_results.append(
                metrics
            )

            model_fold_results.append(
                metrics
            )

            # ------------------------------------------------
            # Store predictions
            # ------------------------------------------------

            for local_index, original_index in enumerate(
                test_idx
            ):

                prediction_records.append(
                    {
                        "dataset": dataset_name,
                        "model": model_name,
                        "fold": fold,
                        "subject_id": str(
                            groups.iloc[
                                original_index
                            ]
                        ),
                        "true_label": int(
                            y.iloc[
                                original_index
                            ]
                        ),
                        "predicted_label": int(
                            y_pred[
                                local_index
                            ]
                        ),
                        "prediction_score": float(
                            y_score[
                                local_index
                            ]
                        ),
                    }
                )

            print(
                f"Fold {fold}: "
                f"F1={metrics['f1']:.4f} | "
                f"Precision={metrics['precision']:.4f} | "
                f"Recall={metrics['recall']:.4f} | "
                f"ROC-AUC={metrics['roc_auc']:.4f}"
                if not np.isnan(metrics["roc_auc"])
                else
                f"Fold {fold}: "
                f"F1={metrics['f1']:.4f} | "
                f"Precision={metrics['precision']:.4f} | "
                f"Recall={metrics['recall']:.4f}"
            )

        # ----------------------------------------------------
        # Train final model on all available supervised data
        # ----------------------------------------------------

        if y.nunique() >= 2:

            final_model = clone(model)

            final_model.fit(
                X,
                y,
            )

            fitted_models[
                model_name
            ] = final_model

    return (
        pd.DataFrame(fold_results),
        pd.DataFrame(prediction_records),
        fitted_models,
    )


# ============================================================
# MODEL SUMMARY
# ============================================================

def summarize_models(
    fold_results: pd.DataFrame,
) -> pd.DataFrame:
    """
    Aggregate fold-level results by model.
    """

    if fold_results.empty:

        return pd.DataFrame()

    metric_columns = [
        "accuracy",
        "precision",
        "recall",
        "f1",
        "roc_auc",
        "pr_auc",
    ]

    summary_rows = []

    for (
        dataset,
        model,
    ), group in fold_results.groupby(
        [
            "dataset",
            "model",
        ]
    ):

        row = {
            "dataset": dataset,
            "model": model,
            "folds": len(group),
        }

        for metric in metric_columns:

            values = group[metric].dropna()

            if len(values) == 0:

                row[
                    f"{metric}_mean"
                ] = np.nan

                row[
                    f"{metric}_std"
                ] = np.nan

            else:

                row[
                    f"{metric}_mean"
                ] = values.mean()

                row[
                    f"{metric}_std"
                ] = values.std(
                    ddof=1
                ) if len(values) > 1 else 0.0

        summary_rows.append(
            row
        )

    summary = pd.DataFrame(
        summary_rows
    )

    if not summary.empty:

        summary = summary.sort_values(
            [
                "dataset",
                "f1_mean",
            ],
            ascending=[
                True,
                False,
            ],
        )

    return summary


# ============================================================
# FEATURE IMPORTANCE
# ============================================================

def extract_feature_importance(
    dataset_name: str,
    model_name: str,
    model,
    feature_columns: List[str],
) -> pd.DataFrame:
    """
    Extract feature importance from models that expose it.

    Supported:
        Random Forest
        XGBoost
    """

    if not hasattr(
        model,
        "named_steps",
    ):

        return pd.DataFrame()

    classifier = model.named_steps.get(
        "classifier"
    )

    if classifier is None:

        return pd.DataFrame()

    importances = None

    # --------------------------------------------------------
    # Tree models
    # --------------------------------------------------------

    if hasattr(
        classifier,
        "feature_importances_",
    ):

        importances = (
            classifier
            .feature_importances_
        )

    if importances is None:

        return pd.DataFrame()

    result = pd.DataFrame(
        {
            "dataset": dataset_name,
            "model": model_name,
            "feature": feature_columns,
            "importance": importances,
        }
    )

    result = result.sort_values(
        "importance",
        ascending=False,
    ).reset_index(
        drop=True
    )

    result["rank"] = (
        np.arange(
            len(result)
        )
        + 1
    )

    return result


# ============================================================
# DATASET VALIDATION REPORT
# ============================================================

def create_dataset_validation_report(
    prepared_datasets: Dict[str, Dict],
) -> pd.DataFrame:
    """
    Create a compact dataset readiness report.
    """

    rows = []

    for dataset_name, info in prepared_datasets.items():

        raw = info.get(
            "raw",
            pd.DataFrame()
        )

        supervised = info.get(
            "supervised",
            pd.DataFrame()
        )

        rows.append(
            {
                "dataset": dataset_name,
                "status": info.get(
                    "status"
                ),
                "candidate_events": len(raw),
                "supervised_events": len(
                    supervised
                ),
                "uncertain_events": info.get(
                    "uncertain_count",
                    0,
                ),
                "unlabeled_events": info.get(
                    "unlabeled_count",
                    0,
                ),
                "subjects": info.get(
                    "subject_count",
                    0,
                ),
                "features": len(
                    info.get(
                        "feature_columns",
                        [],
                    )
                ),
                "artifact_events": info.get(
                    "class_counts",
                    {},
                ).get(
                    1,
                    0,
                ),
                "likely_fetal_events": info.get(
                    "class_counts",
                    {},
                ).get(
                    0,
                    0,
                ),
            }
        )

    return pd.DataFrame(
        rows
    )


# ============================================================
# SAVE JSON EXPERIMENT CONFIGURATION
# ============================================================

def save_experiment_config() -> None:
    """Save reproducibility configuration."""

    config = {
        "random_state": RANDOM_STATE,
        "artifact_label": ARTIFACT_LABEL,
        "fetal_label": FETAL_LABEL,
        "uncertain_label": UNCERTAIN_LABEL,
        "cv": "GroupKFold",
        "max_folds": MAX_FOLDS,
        "minimum_subjects_for_group_cv": (
            MIN_SUBJECTS_FOR_GROUP_CV
        ),
        "xgboost_available": XGBOOST_AVAILABLE,
    }

    with open(
        OUTPUT_DIR
        / "experiment_config.json",
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            config,
            file,
            indent=4,
        )


# ============================================================
# SAVE TEXT SUMMARY
# ============================================================

def save_experiment_summary(
    dataset_report: pd.DataFrame,
    model_summary: pd.DataFrame,
) -> None:
    """
    Save a human-readable experiment summary.
    """

    output_file = (
        OUTPUT_DIR
        / "experiment_summary.txt"
    )

    with open(
        output_file,
        "w",
        encoding="utf-8",
    ) as file:

        file.write(
            "ARTIFACT ML BASELINE EXPERIMENT\n"
        )

        file.write(
            "=" * 80
            + "\n\n"
        )

        file.write(
            "Step 5: Baseline artifact models\n"
        )

        file.write(
            "Step 6: Subject-independent validation\n\n"
        )

        file.write(
            "Label policy:\n"
        )

        file.write(
            "  artifact     -> 1\n"
        )

        file.write(
            "  likely_fetal -> 0\n"
        )

        file.write(
            "  uncertain    -> excluded\n\n"
        )

        file.write(
            "Dataset validation\n"
        )

        file.write(
            "-" * 80
            + "\n"
        )

        if dataset_report.empty:

            file.write(
                "No dataset validation results.\n"
            )

        else:

            file.write(
                dataset_report
                .to_string(
                    index=False
                )
            )

        file.write(
            "\n\nModel comparison\n"
        )

        file.write(
            "-" * 80
            + "\n"
        )

        if model_summary.empty:

            file.write(
                "No valid subject-independent "
                "model results were produced.\n"
            )

        else:

            file.write(
                model_summary
                .to_string(
                    index=False
                )
            )

        file.write(
            "\n\nScientific notes\n"
        )

        file.write(
            "-" * 80
            + "\n"
        )

        file.write(
            "1. Events from the same subject are never "
            "split between train and test folds.\n"
        )

        file.write(
            "2. FOUR_IMU currently contains one subject, "
            "so subject-independent validation is not possible.\n"
        )

        file.write(
            "3. OXFORD currently contains no candidate events "
            "and cannot support supervised artifact ML.\n"
        )

        file.write(
            "4. Uncertain and unlabeled events are excluded "
            "from supervised training.\n"
        )

        file.write(
            "5. This experiment does not perform artifact removal.\n"
        )


# ============================================================
# MAIN DATASET PROCESSING
# ============================================================

def process_dataset(
    dataset_name: str,
    path: Path,
):
    """
    Load, prepare, and optionally validate one dataset.
    """

    print_header(
        f"{dataset_name} ARTIFACT ML DATASET"
    )

    print(
        f"Input: {path}"
    )

    try:

        raw_df = load_candidate_events(
            dataset_name,
            path,
        )

    except Exception as exc:

        print(
            f"\n❌ Failed to load {dataset_name}: "
            f"{type(exc).__name__}: {exc}"
        )

        return {
            "status": "LOAD_FAILED",
            "dataset": dataset_name,
            "raw": pd.DataFrame(),
        }

    return prepare_dataset(
        dataset_name,
        raw_df,
    )


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    """
    Main experiment driver.
    """

    warnings.filterwarnings(
        "ignore",
        category=FutureWarning,
    )

    print_header(
        "ARTIFACT ML BASELINE + SUBJECT-INDEPENDENT VALIDATION"
    )

    print(
        "This stage implements Steps 5 and 6."
    )

    print(
        "\nNo artifact removal is performed."
    )

    print(
        "No fetal movement classifier is trained."
    )

    print(
        "\nProject root:"
    )

    print(
        PROJECT_ROOT
    )

    print(
        "\nInput directory:"
    )

    print(
        INPUT_DIR
    )

    print(
        "\nOutput directory:"
    )

    print(
        OUTPUT_DIR
    )

    # --------------------------------------------------------
    # Setup
    # --------------------------------------------------------

    create_output_directories()

    save_experiment_config()

    # --------------------------------------------------------
    # Prepare datasets
    # --------------------------------------------------------

    prepared_datasets = {}

    for dataset_name, path in DATASET_FILES.items():

        prepared_datasets[
            dataset_name
        ] = process_dataset(
            dataset_name,
            path,
        )

    # --------------------------------------------------------
    # Dataset validation report
    # --------------------------------------------------------

    print_header(
        "ARTIFACT EVENT DATASET VALIDATION SUMMARY"
    )

    dataset_report = (
        create_dataset_validation_report(
            prepared_datasets
        )
    )

    if dataset_report.empty:

        print(
            "No dataset results available."
        )

    else:

        print(
            dataset_report
            .to_string(
                index=False
            )
        )

    dataset_report.to_csv(
        OUTPUT_DIR
        / "dataset_validation.csv",
        index=False,
    )

    # --------------------------------------------------------
    # Step 5 + 6
    # --------------------------------------------------------

    all_fold_results = []
    all_predictions = []
    all_feature_importance = []

    # --------------------------------------------------------
    # Process each dataset independently
    # --------------------------------------------------------

    for dataset_name, info in (
        prepared_datasets.items()
    ):

        if info.get("status") != "READY":

            print(
                f"\nSkipping {dataset_name}: "
                f"{info.get('status')}"
            )

            continue

        X = info["X"]
        y = info["y"]
        groups = info["groups"]
        feature_columns = info[
            "feature_columns"
        ]

        # ----------------------------------------------------
        # Subject-independent CV
        # ----------------------------------------------------

        (
            fold_results,
            predictions,
            fitted_models,
        ) = run_subject_independent_cv(
            dataset_name,
            X,
            y,
            groups,
            feature_columns,
        )

        # ----------------------------------------------------
        # Store results
        # ----------------------------------------------------

        if not fold_results.empty:

            all_fold_results.append(
                fold_results
            )

        if not predictions.empty:

            all_predictions.append(
                predictions
            )

        # ----------------------------------------------------
        # Save fitted models
        # ----------------------------------------------------

        for (
            model_name,
            fitted_model,
        ) in fitted_models.items():

            model_file = (
                MODEL_DIR
                / (
                    f"{dataset_name.lower()}"
                    f"_{model_name.lower()}"
                    f".joblib"
                )
            )

            joblib.dump(
                fitted_model,
                model_file,
            )

            print(
                f"Saved model: {model_file}"
            )

            # ------------------------------------------------
            # Feature importance
            # ------------------------------------------------

            importance = (
                extract_feature_importance(
                    dataset_name,
                    model_name,
                    fitted_model,
                    feature_columns,
                )
            )

            if not importance.empty:

                all_feature_importance.append(
                    importance
                )

    # --------------------------------------------------------
    # Combine fold results
    # --------------------------------------------------------

    if all_fold_results:

        fold_results_df = pd.concat(
            all_fold_results,
            ignore_index=True,
        )

    else:

        fold_results_df = pd.DataFrame()

    # --------------------------------------------------------
    # Combine predictions
    # --------------------------------------------------------

    if all_predictions:

        predictions_df = pd.concat(
            all_predictions,
            ignore_index=True,
        )

    else:

        predictions_df = pd.DataFrame()

    # --------------------------------------------------------
    # Combine feature importance
    # --------------------------------------------------------

    if all_feature_importance:

        feature_importance_df = pd.concat(
            all_feature_importance,
            ignore_index=True,
        )

    else:

        feature_importance_df = pd.DataFrame()

    # --------------------------------------------------------
    # Save fold results
    # --------------------------------------------------------

    fold_results_df.to_csv(
        OUTPUT_DIR
        / "fold_results.csv",
        index=False,
    )

    # --------------------------------------------------------
    # Save predictions
    # --------------------------------------------------------

    predictions_df.to_csv(
        OUTPUT_DIR
        / "predictions.csv",
        index=False,
    )

    # --------------------------------------------------------
    # Save feature importance
    # --------------------------------------------------------

    feature_importance_df.to_csv(
        OUTPUT_DIR
        / "feature_importance.csv",
        index=False,
    )

    # --------------------------------------------------------
    # Model comparison
    # --------------------------------------------------------

    model_summary = summarize_models(
        fold_results_df
    )

    model_summary.to_csv(
        OUTPUT_DIR
        / "model_comparison.csv",
        index=False,
    )

    # --------------------------------------------------------
    # Human-readable report
    # --------------------------------------------------------

    save_experiment_summary(
        dataset_report,
        model_summary,
    )

    # ========================================================
    # FINAL OUTPUT
    # ========================================================

    print_header(
        "ARTIFACT ML EXPERIMENT COMPLETE"
    )

    print(
        "\nOutput directory:"
    )

    print(
        OUTPUT_DIR
    )

    print(
        "\nGenerated files:"
    )

    print(
        "  dataset_validation.csv"
    )

    print(
        "  fold_results.csv"
    )

    print(
        "  predictions.csv"
    )

    print(
        "  model_comparison.csv"
    )

    print(
        "  feature_importance.csv"
    )

    print(
        "  experiment_config.json"
    )

    print(
        "  experiment_summary.txt"
    )

    print(
        "  models/"
    )

    # --------------------------------------------------------
    # Final model summary
    # --------------------------------------------------------

    if model_summary.empty:

        print(
            "\n⚠ No valid subject-independent "
            "model experiment was completed."
        )

        print(
            "\nThis is expected if the candidate events "
            "are not yet manually labeled or if there "
            "are insufficient subjects."
        )

    else:

        print_header(
            "MODEL COMPARISON"
        )

        display_columns = [
            "dataset",
            "model",
            "folds",
            "f1_mean",
            "f1_std",
            "precision_mean",
            "recall_mean",
            "roc_auc_mean",
            "pr_auc_mean",
        ]

        available_columns = [
            column
            for column in display_columns
            if column in model_summary.columns
        ]

        print(
            model_summary[
                available_columns
            ].to_string(
                index=False
            )
        )

        print(
            "\nBest baseline is ranked primarily by "
            "mean F1 across subject-independent folds."
        )

    print(
        "\n"
        + "=" * 80
    )

    print(
        "STEP 5 + STEP 6 FINISHED"
    )

    print(
        "=" * 80
    )

    print(
        "\nDo NOT integrate the detector into the "
        "movement pipeline yet."
    )

    print(
        "First inspect model performance, "
        "fold predictions, and feature importance."
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()